###

POST http://localhost:3000/register 
Content-Type: application/json


{
    "name":"Ankaiah",
    "password":"Anki@123",
    "mobile":9390304789,
    "address":"Nellore"
}


###

POST http://localhost:3000/register 
Content-Type: application/json


{
    "name":"Raju",
    "password":"Raju@123",
    "mobile":8976458909,
    "address":"Hyderabad"
}

###

POST http://localhost:3000/login
Content-Type: application/json


{
    "name":"Ankaiah",
    "password":"Anki@123"
    

}

###

POST http://localhost:3000/login
Content-Type: application/json


{
    "name":"Raju",
    "password":"Raju@123"
    
}


###

POST http://localhost:3000/createDairyEntrie
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFua2FpYWgiLCJpYXQiOjE3MTMwNzMzNjJ9.FihDJedCMgD8m-IvSnVPPUftR8vLVnwNid-OnsYU3U4
Content-Type: application/json


{
    "title":"England Tour",
    "description":"The England Tour diary entry chronicles an exhilarating journey across the picturesque landscapes and vibrant cities of England",
    "date":"2024-08-12"
}



###

GET http://localhost:3000/getDairyEntries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFua2FpYWgiLCJpYXQiOjE3MTMwNzMzNjJ9.FihDJedCMgD8m-IvSnVPPUftR8vLVnwNid-OnsYU3U4



###

PUT http://localhost:3000/updateDairyEntrie/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFua2FpYWgiLCJpYXQiOjE3MTMwNzMzNjJ9.FihDJedCMgD8m-IvSnVPPUftR8vLVnwNid-OnsYU3U4
Content-Type: application/json


{
    "title":"Brazil Tour",
    "description":"The Brazil Tour diary entry chronicles an exhilarating journey across the picturesque landscapes and vibrant cities of England",
    "date":"2024-11-22"
}


###

DELETE http://localhost:3000/deleteDairyEntrie/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFua2FpYWgiLCJpYXQiOjE3MTMwNzMzNjJ9.FihDJedCMgD8m-IvSnVPPUftR8vLVnwNid-OnsYU3U4





