###

POST http://localhost:3000/register 
Content-Type: application/json


{
    "name":"Ramu",
    "password":"ramu@123",
    "mobile":8883334449,
    "address":"Kadapa"
}


###

POST http://localhost:3000/register 
Content-Type: application/json


{
    "name":"Raju",
    "password":"Raju@123",
    "mobile":8976458909,
    "address":"Hyderabad"
}

###

POST http://localhost:3000/login
Content-Type: application/json


{
    "name":"Ramu",
    "password":"ramu@123"

}

###

POST http://localhost:3000/login
Content-Type: application/json


{
    "name":"Raju",
    "password":"Raju@123"
    
}


###

POST http://localhost:3000/createDairyEntrie
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhbXUiLCJpYXQiOjE3MTMxNDkxNzJ9.jfoXfA7CoPL51i8_4pwPqMyYGHCGQF4CyOgAzRqNZbY
Content-Type: application/json


{
    "title":"Spain Tour",
    "description":"The Spain Tour diary entry chronicles an exhilarating journey across the picturesque landscapes and vibrant cities of England",
    "date":"2024-12-22"
}



###

GET http://localhost:3000/getDairyEntries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhbXUiLCJpYXQiOjE3MTMxNDkxNzJ9.jfoXfA7CoPL51i8_4pwPqMyYGHCGQF4CyOgAzRqNZbY



###

PUT http://localhost:3000/updateDairyEntrie/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhbXUiLCJpYXQiOjE3MTMxNDkxNzJ9.jfoXfA7CoPL51i8_4pwPqMyYGHCGQF4CyOgAzRqNZbY
Content-Type: application/json


{
    "title":"Brazil Tour",
    "description":"The Brazil Tour diary entry chronicles an exhilarating journey across the picturesque landscapes and vibrant cities of England",
    "date":"2024-11-22"
}


###

DELETE http://localhost:3000/deleteDairyEntrie/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhbXUiLCJpYXQiOjE3MTMxNDkxNzJ9.jfoXfA7CoPL51i8_4pwPqMyYGHCGQF4CyOgAzRqNZbY





